___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list= [5,10,15,20,25]
arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
arr2=np.ones((4,4), dtype=int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
arr2[i==1]=7
arr2

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
arr3= np.arange(2,18,2)
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
arr8 = np.arange(0,25).reshape(5,5)
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
arr9= np.linspace(0,24,25).reshape(5,5)
arr9

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [ ]:
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
arr10 = np.random.rand(5)
arr10


array([0.99223254, 0.25789766, 0.65691317, 0.75859297, 0.93842475])

#### 11. Create random normal distributed 5x5 array

In [ ]:
arr11= np.random.randn(25).reshape(5,5)
arr11

array([[ 0.12873732,  3.04028317,  0.29583212,  0.23005634,  0.7758584 ],
       [ 0.34955763, -2.61964262,  1.22759821, -0.58360235,  0.71804826],
       [ 1.52498943,  2.39366858, -0.24658118, -0.30281526,  1.18899869],
       [-0.9928476 ,  0.92771956, -1.56046454, -0.08090608,  0.26282048],
       [-0.29392505, -1.23919964, -1.31649424, -0.12794761, -0.72987111]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
arr12= np.random.randint(20,50,12).reshape(3,4)
arr12


array([[30, 37, 24, 25],
       [22, 47, 43, 27],
       [28, 29, 26, 42]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
arr13 = np.array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]]).reshape (6,8)
arr13

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
ranarr

NameError: ignored

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
#reshape with -1


array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
arr14 = arr13.reshape(6,-1)
arr14

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat2=mat[1:3, 1:3]
mat2

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat3 = mat[0,::]

array([1, 2, 3, 4])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat4= mat[1,0:3:2]
mat4

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat=np.arange(1,17).reshape(4,4)
birinci=mat[1,0]
ikinci=mat[3,1]
print(birinci)
print(ikinci)
deneme=mat[slice(birinci,ikinci)]
deneme

5
14


array([], shape=(0, 4), dtype=int64)

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
mat[:,2]=77
mat
mat19= mat[1:4:2,2]
mat19

array([77, 77])

In [ ]:
array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat20 = mat[mat<10]
mat20
toplam=sum(mat20)
toplam


35

In [ ]:
mat21= mat[mat>12]
mat21

array([77, 77, 77, 13, 14, 77, 16])

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
deneme= np.array([78, 79, 81, 18, 20, 85, 25])
np.std(deneme)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
toplam= sum(mat[:,1])
toplam

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[2]

array([ 9, 10, 11, 12])

In [ ]:
np.median(mat[2])


10.5

In [ ]:
np.mean(mat[2]) #mean


10.5

In [ ]:
np.std(mat[2])


1.118033988749895

# Pandas Section

In [ ]:
import pandas as pd

In [7]:
sal=pd.read_csv("/content/drive/MyDrive/Salaries.csv")

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [ ]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [ ]:
len(sal.groupby(["Year"]))

4

**Print out max and avg Totalpay**

In [ ]:
max(sal.TotalPay)


567595.43

In [ ]:
sal["TotalPay"].mean()


74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
adet=sal[sal["TotalPay"]>74768.321971703].count()
adet

Id                  20096
EmployeeName        20096
JobTitle            20096
BasePay             20096
OvertimePay         20096
OtherPay            20096
Benefits             4249
TotalPay            20096
TotalPayBenefits    20096
Year                20096
Notes                   0
Agency              20096
Status                  0
dtype: int64

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal[sal["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]


Id        EmployeeName  ...         Agency  Status
36156  36157      PAULETTE ADAMS  ...  San Francisco     NaN
36157  36158       KAUKAB MOHSIN  ...  San Francisco     NaN
36158  36159  JOSEPHINE MCCREARY  ...  San Francisco     NaN

[3 rows x 13 columns]

**What are the unique Jobs in dataset?**

In [ ]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Senior Electrical Inpsector', 'Electrical Inspector',
       'Ex Asst to Ex Dir, Retirement'], dtype=object)

**List 3 least common Jobs**

In [ ]:
sal["JobTitle"].value_counts().tail(3)


WIRE ROPE CABLE MAINTENANCE SUPERVISOR    1
LIEUTENANT II (POLICE DEPARTMENT)         1
LEGISLATIVE CALENDAR CLERK                1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
sal[(sal["TotalPay"]>74768.321971703)&(sal["Year"]==2012)].count()

Id                  4249
EmployeeName        4249
JobTitle            4249
BasePay             4249
OvertimePay         4249
OtherPay            4249
Benefits            4249
TotalPay            4249
TotalPayBenefits    4249
Year                4249
Notes                  0
Agency              4249
Status                 0
dtype: int64

**How many people have the word Manager in their job title?**

In [ ]:
sal[sal["JobTitle"].apply(lambda x : "Manager" in x)]["JobTitle"].value_counts().sum()



496

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [9]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [11]:
sal_new=sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [15]:
sal_new=sal.iloc[:,1:8]
sal_new

EmployeeName  ...   TotalPay
0          NATHANIEL FORD  ...  567595.43
1            GARY JIMENEZ  ...  538909.28
2          ALBERT PARDINI  ...  335279.91
3       CHRISTOPHER CHONG  ...  332343.61
4         PATRICK GARDNER  ...  326373.19
...                   ...  ...        ...
148649      Roy I Tillery  ...       0.00
148650       Not provided  ...       0.00
148651       Not provided  ...       0.00
148652       Not provided  ...       0.00
148653          Joe Lopez  ...    -618.13

[148654 rows x 7 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [29]:
sonbitti = sal[sal["TotalPay"]<sal["TotalPay"].mean()]
sonbitti

Id       EmployeeName  ...         Agency  Status
15847    15848  TATYANA ROTENBERG  ...  San Francisco     NaN
15848    15849        WINSTON HOM  ...  San Francisco     NaN
15849    15850       CRAIG RIGLER  ...  San Francisco     NaN
15850    15851          WENDY TAN  ...  San Francisco     NaN
15851    15852     KENNETH BREWER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN
148653  148654          Joe Lopez  ...  San Francisco     NaN

[79165 rows x 13 columns]